databases:
  - name: seguimiento-db
    plan: free
    databaseName: seguimiento
    user: seguimiento

services:
  - type: web
    name: seguimiento-actividades
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: DATABASE_URL
        fromDatabase:
          name: seguimiento-db
          property: connectionString
